### PR TITLE
Fix not accounting for cells covering gaps

### LINKED ISSUE #17: Issue w/ gap logic (not accounting for previously placed cell splitting the current turn
Screen Shot 2021-04-23 at 4 44 40 PM

### PR DESCRIPTION
**Pull request by drewrodrigues**
Before, the following would fail:
Screen Shot 2021-04-25 at 1 51 54 PM

Now this has been accounted for in validation logic

### CODE REVIEW

File: src/utils/validate.ts [hunk 1]
```diff
@@ -25,28 +25,39 @@ function _validateCenterCovered(cells: Cells, currentTurn: CurrentTurn[]) {
...
-function _validateNoGaps(currentTurn: CurrentTurn[], direction: Direction) {
-  const rowOrColumnValues = currentTurn.map(
-    (cell) => cell[direction === Direction.Vertical ? "row" : "column"]
-  );
+function _validateNoGaps(
+  cells: Cells,
+  currentTurn: CurrentTurn[],
+  direction: Direction
+) {
+  const property = direction === Direction.Vertical ? "row" : "column";
```
Comment (viviana-aline) [inline src/utils/validate.ts]: remove property

**Review by viviana-aline — APPROVED** [review]
